### ISSUE TITLE
event-stream@3.3.6 issue

### ISSUE THREAD

**Issue by rylxes** [MaSSTeck/pqm-api#1]
i cloned the project afresh, ... and did 'npm install', .... i got the error 

404 Not Found: event-stream@3.3.6

though, upgrading nodemon to ^1.18.7 fixed the issue

**Comment by Seunope** [comment]
Yeah! I experienced similar issue with another node project. I had to delete my package-lock.json and run 'npm install' before it could work. Thanks for providing this fix.
